// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBf8dO04Gjrt_Z3bDeRl3UdmVO5KzPGM8',
    appId: '1:218703842916:web:fb3064c5b11b89c45d5971',
    messagingSenderId: '218703842916',
    projectId: 'swachh-e7e6e',
    authDomain: 'swachh-e7e6e.firebaseapp.com',
    storageBucket: 'swachh-e7e6e.appspot.com',
    measurementId: 'G-86L1WJ8L49',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCSeNPwD3a6KkvUI3pJmpN7GLcBeGF61Q',
    appId: '1:218703842916:android:e71e0d037c9988735d5971',
    messagingSenderId: '218703842916',
    projectId: 'swachh-e7e6e',
    storageBucket: 'swachh-e7e6e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBi5MMXXWRVp4oflJTijbwquIyds9qbclI',
    appId: '1:218703842916:ios:319e0c0e1f9047125d5971',
    messagingSenderId: '218703842916',
    projectId: 'swachh-e7e6e',
    storageBucket: 'swachh-e7e6e.appspot.com',
    iosClientId: '218703842916-l3dri92q9df06p0hmdh2pkjukigm2klu.apps.googleusercontent.com',
    iosBundleId: 'com.example.mehahackuser',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBi5MMXXWRVp4oflJTijbwquIyds9qbclI',
    appId: '1:218703842916:ios:319e0c0e1f9047125d5971',
    messagingSenderId: '218703842916',
    projectId: 'swachh-e7e6e',
    storageBucket: 'swachh-e7e6e.appspot.com',
    iosClientId: '218703842916-l3dri92q9df06p0hmdh2pkjukigm2klu.apps.googleusercontent.com',
    iosBundleId: 'com.example.mehahackuser',
  );
}
